zuul:  
  routes:
    character-service:
      path: /api/characters/**
      url: http://localhost:8081/api/v1/characters
    house-service:
      path: /api/house/**
      url: http://localhost:8082/api/v1/house
