zuul:  
  routes:
    character-service:
      path: /api/characters/**
      url: http://characterservice:8080/api/v1/characters
    house-service:
      path: /api/house/**
      url: http://houseservice:8080/api/v1/house
